# Generated by Django 5.2.2 on 2025-06-10 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='province',
            name='district',
        ),
        migrations.RemoveField(
            model_name='province',
            name='province_cm',
        ),
    ]
