# Generated by Django 5.2.2 on 2025-06-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_remove_province_district_remove_province_province_cm'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='province_cm',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]

