# Generated by Django 5.2.2 on 2025-06-13 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_province_province_cm'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Countries',
            new_name='country',
        ),
    ]
