# Generated by Django 5.2.2 on 2025-06-13 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=25, unique=True)),
                ('phone_no', models.IntegerField(max_length=10)),
                ('contact_date', models.DateTimeField(default=datetime.datetime(2025, 6, 13, 13, 23, 54, 136455))),
                ('address', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=250)),
            ],
        ),
    ]
